const english = {
  welcome: 'Welcome',
  forex: {
    title: 'Enter Trade Details',
    edit_title: 'Edit Trade Details',
    entry_price: 'Entry Price',
    entry: 'Entry',
    ratio: 'Ratio',
    risk: 'Risk',
    reward: 'Reward',
    pips: 'Pips',
    take_profit: 'Take Profit',
    stop_loss: 'Stop Loss',
    gain: 'Gain',
    loss: 'Loss',
    lot: 'Lot Size',
    pip_value: 'Pip Value',
    buy: 'Buy',
    sell: 'Sell',
    weekly_pips: 'Weekly Pips',
    monthly_pips: 'Monthly Pips',
    sl: 'S/L',
    tp: 'T/P',
    rules: 'Enter 3 standard S/L and T/P pips values (This will be suggested for every trade with auto calculated S/L and T/P)',
    add_take_profit: 'Add Take Profit',
    add_stop_loss: 'Add Stop Loss',
    enter_pips: 'Enter pips',
    profit: 'Profit',
    take_profit_rules: 'Take Profit Rules',
    stop_loss_rules: 'Stop Loss Rules',
  },
  common: {
    confirm: 'Confirm',
    cancel: 'Cancel',
    remove: 'Remove',
    edit: 'Edit',
    delete: 'Delete',
    duplicate: 'Duplicate',
    save: 'Save',
    update: 'Update',
    pending: 'Pending',
    add: 'Add',
    close: 'Close',
    open: 'Open',
    closed: 'Closed',
    close_in_profit: 'Closed in profit',
    close_in_loss: 'Closed in loss',
    reached_tp:  'Reached T/P',
    reached_sl: 'Reached S/L'
  },
  placeholder: {
    entry: 'Enter entry price',
    forex: 'Search for currency',
    profit: 'Enter take profit',
    loss: 'Enter stop loss',
    lot: 'Enter lot size',
    pips: 'Enter pip value',
    journal: 'Start journaling...'

  },
  language: {
    language: 'Language',
    select_language: 'Select Language',
    english: 'English',
    french: 'French',
    en: 'English',
    fr: 'French',
  },
  user:{
    personal_information: 'Personal Information',
    last_name: 'Last Name',
    first_name: 'First Name',
    email: 'Email',
    password: 'Password',
    confirm_password: 'Confirm Password',
    change_password: 'Change Password',
    enter_first_name: 'Enter first name',
    enter_last_name: 'Enter last name',
    enter_email: 'Enter email address',
    change_password_confirmation: 'Are you sure you want to change your password?',
    profile_update_failed: 'Profile update failed',
  },
  currency: {
    select_account_currency: 'Select Account Currency',
    cad: 'Canadian Dollar (CAD)',
    usd: 'United States Dollar (USD)',
    aud: 'Australian Dollar (AUD)',
    nzd: 'New Zealand Dollar (NZD)',
    eur: 'Euro (EUR)',
    gbp: 'British Pound (GBP)',
    jpy: 'Japanese Yen (JPY)',
    chf: 'Swiss Franc (CHF)',
    cny: 'Chinese Yuan (CNY)',
  },
  short_currency: {
    cad: 'CAD',
    usd: 'USD',
    aud: 'AUD',
    nzd: 'NZD',
    eur: 'EUR',
    gbp: 'GBP',
    jpy: 'JPY',
    chf: 'CHF',
    cny: 'CNY',
  },
  type: 'Execution Type',
  rate: 'Exchange Rate',
  account_currency: 'Account Currency',
  password: 'Password',
  confirm_password: 'Confirm Password',
  email: 'Email',
  logout: 'Logout',
  login: 'Login',
  signup: 'Sign Up',
  signin: 'Sign In',
  signin_with: 'or sign in with',
  login_invalid: 'Invalid email or password',
  password_invalid: 'Password is not a match',
  password_rule: 'Password must be least 8 characters, one letter and one number',
  reset_password: 'Reset Password',
  form_incomplete: 'Complete the form before signing up',
  no_account: 'Don\'t have an account?',
  hide_password: 'Hide Password',
  show_password: 'Show Password',
  invalid_email: 'The email is invalid',
  fname: 'First Name',
  lname: 'Last Name',
  zenlot_logo: 'Zenlot Icon',
  trading_overview: 'Trading Overview',
  weekly_analysis: 'Weekly Analysis',
  monthly_analysis: 'Monthly Analysis',
  weekly_pips: 'Weekly Pips',
  monthly_pips: 'Monthly Pips',
  active_trades: 'Active Trades',
  trades: 'Trades',
  net: 'Net',
  no_trade_entered: 'No trade entered',
  available_analyses: 'Available Analyses',
  no_available_analyses: 'No available Analyses',
  selected_analyses: 'Selected Analyses',
  no_selected_analyses: 'No selected Analyses',
  symbol: 'Symbol',
  tap_to_enter_trade: 'Tap to enter a trade',
  no_internet_connection: 'No internet connection',
  duplicate_trade: 'Duplicate Trade',
  edit_trade: 'Edit Trade',
  delete_trade: 'Delete Trade',
  pull_to_refresh: 'Pull to refresh',
  hide_note: 'Hide Note',
  show_note: 'Show Note',
  logout_confirmation: 'Are you sure you want to logout?',
  profile: 'Profile',
  settings: 'Settings',
  preferences: 'Preferences',
  base_currency: 'Base Currency',
  rules: 'Rules',
  trading_rules: 'Trading Rules',
  current_password: 'Current Password',
  new_password: 'New Password',
  confirm_new_password: 'Confirm New Password',
  change_password: 'Change Password',
  change_password_confirmation: 'Are you sure you want to change your password?',
  change_password_error: 'Failed to change password',
  history: 'History',
  journals: 'Journals',
  home: 'Home',
  update_error: 'Update Error',
  password_update_failed: "Password update failed",
  password_too_short: 'Password is too short',
  passwords_dont_match: 'Passwords do not match',
  password_updated: 'Password updated successfully',
  wrong_exisiting_password: 'Current password is wrong'
}

export default english;