import { success } from "zod";

const english = {
  welcome: 'Welcome',
  slogan: 'Master risk management with ease',
  forex: {
    title: 'Enter Trade Details',
    edit_title: 'Edit Trade Details',
    entry_price: 'Entry Price',
    entry: 'Entry',
    ratio: 'Ratio',
    risk: 'Risk',
    reward: 'Reward',
    pips: 'Pips',
    take_profit: 'Take Profit',
    stop_loss: 'Stop Loss',
    gain: 'Gain',
    loss: 'Loss',
    lot: 'Lot Size',
    pip_value: 'Pip Value',
    buy: 'Buy',
    sell: 'Sell',
    weekly_pips: 'Weekly Pips',
    monthly_pips: 'Monthly Pips',
    sl: 'S/L',
    tp: 'T/P',
    rules: 'Enter 3 standard S/L and T/P pips values (This will be suggested for every trade with auto calculated S/L and T/P)',
    add_take_profit: 'Add Take Profit',
    add_stop_loss: 'Add Stop Loss',
    enter_pips: 'Enter pips',
    profit: 'Profit',
    take_profit_rules: 'Take Profit Rules',
    stop_loss_rules: 'Stop Loss Rules',
  },
  common: {
    confirm: 'Confirm',
    cancel: 'Cancel',
    remove: 'Remove',
    edit: 'Edit',
    delete: 'Delete',
    duplicate: 'Duplicate',
    save: 'Save',
    update: 'Update',
    pending: 'Pending',
    add: 'Add',
    close: 'Close',
    open: 'Open',
    closed: 'Closed',
    close_in_profit: 'Closed in profit',
    close_in_loss: 'Closed in loss',
    reached_tp:  'Reached T/P',
    reached_sl: 'Reached S/L'
  },
  placeholder: {
    entry: 'Enter entry price',
    forex: 'Search for currency',
    profit: 'Enter take profit',
    loss: 'Enter stop loss',
    lot: 'Enter lot size',
    pips: 'Enter pip value',
    journal: 'Start journaling...'

  },
  language: {
    language: 'Language',
    select_language: 'Select Language',
    en: 'English',
    fr: 'French',
    es: 'Spanish'
  },
  user:{
    name: 'Name',
    personal_information: 'Personal Information',
    last_name: 'Last Name',
    first_name: 'First Name',
    email: 'Email',
    enter_first_name: 'Enter first name',
    enter_last_name: 'Enter last name',
    enter_email: 'Enter email address',
    profile_update_failed: 'Profile update failed',
    member_since: 'Creation date',
    appearance_language: 'Appearance and Language',
    appearance: 'Appearance',
    appearance_language_desc: 'Choose your language and how the app looks.',
    select_theme: 'Select theme',
    preview_title: 'Preview',
    preview_desc: 'This is how text and surfaces look with the selected theme.',
    security: 'Security',
    authentication_method: 'Authentication Method',
    timezone: 'Timezone',
    edit_profile: 'Edit Profile'

  },
  appearance: {
    light: 'Light',
    dark: 'Dark',
    system: 'System'
  },
  currency: {
    select_account_currency: 'Select Account Currency',
    cad: 'Canadian Dollar (CAD)',
    usd: 'United States Dollar (USD)',
    aud: 'Australian Dollar (AUD)',
    nzd: 'New Zealand Dollar (NZD)',
    eur: 'Euro (EUR)',
    gbp: 'British Pound (GBP)',
    jpy: 'Japanese Yen (JPY)',
    chf: 'Swiss Franc (CHF)',
    cny: 'Chinese Yuan (CNY)',
  },
  short_currency: {
    cad: 'CAD',
    usd: 'USD',
    aud: 'AUD',
    nzd: 'NZD',
    eur: 'EUR',
    gbp: 'GBP',
    jpy: 'JPY',
    chf: 'CHF',
    cny: 'CNY',
  },
  password: {
    password: 'Password',
    confirm: 'Confirm Password',
    change: 'Change Password',
    change_desc: 'Update your password to keep your account secure.',
    change_confirmation: 'Are you sure you want to change your password?',
    mismatch: 'Password is not a match',
    rule: 'Password must be least 8 characters, one letter and one number',
    reset: 'Reset Password',
    hide: 'Hide Password',
    show: 'Show Password',
    current: 'Current Password',
    current_required: 'Current password is required',
    new: 'New Password',
    confirm_required: 'Please confirm your new password',
    confirm_new: 'Confirm New Password',
    new_required: 'New password is required',
    change_error: 'Failed to change password',
    update_failed: "Password update failed",
    too_short: 'Password must be at least 8 characters.',
    updated: 'Password updated successfully',
    current_error: 'Current password is wrong',
    strength: 'Password Strength',
    strong: 'Strong',
    moderate: 'Moderate',
    weak: 'Weak',
    very_weak: 'Very Weak',
    same_as_current: 'New password must be different from current password.',
  },
  default: {
    tp: 'Default T/P',
    sl: 'Default S/L',
    lot: 'Default Lot Size',
  },
  type: 'Execution Type',
  rate: 'Exchange Rate',
  account_currency: 'Account Currency',
  email: 'Email',
  logout: 'Logout',
  login: 'Login',
  signup: 'Sign Up',
  signin: 'Sign In',
  signin_with: 'or sign in with',
  login_invalid: 'Invalid email or password',
  form_incomplete: 'Complete the form before signing up',
  no_account: 'Don\'t have an account?',
  invalid_email: 'The email is invalid',
  fname: 'First Name',
  lname: 'Last Name',
  zenlot_logo: 'Zenlot Icon',
  trading_overview: 'Trading Overview',
  weekly_analysis: 'Weekly Analysis',
  monthly_analysis: 'Monthly Analysis',
  weekly_pips: 'Weekly Pips',
  monthly_pips: 'Monthly Pips',
  active_trades: 'Active Trades',
  trades: 'Trades',
  net: 'Net',
  no_trade_entered: 'No trade entered',
  available_analyses: 'Available Analyses',
  no_available_analyses: 'No available Analyses',
  selected_analyses: 'Selected Analyses',
  no_selected_analyses: 'No selected Analyses',
  symbol: 'Symbol',
  tap_to_enter_trade: 'Tap to enter a trade',
  no_internet_connection: 'No internet connection',
  duplicate_trade: 'Duplicate Trade',
  edit_trade: 'Edit Trade',
  delete_trade: 'Delete Trade',
  pull_to_refresh: 'Pull to refresh',
  hide_note: 'Hide Note',
  show_note: 'Show Note',
  logout_confirmation: 'Are you sure you want to logout?',
  profile: 'Profile',
  settings: 'Settings',
  preferences: 'Preferences',
  base_currency: 'Base Currency',
  rules: 'Rules',
  trading_rules: 'Trading Rules',
  history: 'History',
  journals: 'Journals',
  home: 'Home',
  update_error: 'Update Error',
  no_active_trades: 'No active trades',
  add_analytic_overview: "Tap to add analytic overview",
  success: 'Success',
  show_gain_in_loss: 'Show Gain/Loss in ',
  show_gain_in_loss_desc: 'Switch between displaying gain/loss in pips or account currency.',
  modify_trading_rules: 'Modify your trading rules',
  app_information: 'App Information',
  app_version: 'App Version',
  last_update: 'Last Update',
  account_actions: 'Account Actions',

}

export default english;