const french = {
  welcome: 'Bienvenue',
  forex: {
    title: 'Entrer les détails de la transaction',
    edit_title: 'Modifier les détails de la transaction',
    entry_price: 'Prix d`entrée',
    entry: 'Entrée',
    ratio: 'Ratio',
    risk: 'Risque',
    reward: 'Récompense',
    pips: 'Pips',
    take_profit: 'Prendre profit',
    stop_loss: 'Stop loss',
    gain: 'Gain',
    loss: 'Perte',
    lot: 'Taille du lot',
    pip_value: 'Valeur du pip',
    buy: 'Acheter',
    sell: 'Vendre',
    weekly_pips: 'Pips hebdomadaires',
    monthly_pips: 'Pips mensuels',
    sl: 'S/L',
    tp: 'T/P',
    rules: 'Entrez 3 valeurs standard de pips S/L et T/P (elles seront suggérées pour chaque transaction avec calcul automatique de S/L et T/P)',
    add_take_profit: 'Ajouter un take profit',
    add_stop_loss: 'Ajouter un stop loss',
    enter_pips: 'Entrez les pips',
    profit: 'Profit',
    take_profit_rules: 'Règles de take profit',
    stop_loss_rules: 'Règles de stop loss',
  },
  common: {
    confirm: 'Confirmer',
    cancel: 'Annuler',
    remove: 'Supprimer',
    edit: 'Modifier',
    delete: 'Supprimer',
    duplicate: 'Dupliquer',
    save: 'Enregistrer',
    update: 'Mettre à jour',
    pending: 'En attente',
    add: 'Ajouter',
    close: 'Fermer',
    open: 'Ouvrir',
    closed: 'Fermé',
    close_in_profit: 'Fermé en profit',
    close_in_loss: 'Fermé en perte',
    reached_tp: 'T/P atteint',
    reached_sl: 'S/L atteint'
  },
  placeholder: {
    entry: 'Entrez le prix d’entrée',
    forex: 'Rechercher une devise',
    profit: 'Entrez le take profit',
    loss: 'Entrez le stop loss',
    lot: 'Entrez la taille du lot',
    pips: 'Entrez la valeur du pip',
    journal: 'Commencez à écrire dans le journal...'
  },
  language: {
    language: 'Langue',
    select_language: 'Sélectionner la langue',
    english: 'Anglais',
    french: 'Français',
    en: 'Anglais',
    fr: 'Français',
  },
  user: {
    personal_information: 'Informations personnelles',
    last_name: 'Nom',
    first_name: 'Prénom',
    email: 'E-mail',
    password: 'Mot de passe',
    confirm_password: 'Confirmer le mot de passe',
    change_password: 'Changer le mot de passe',
    enter_first_name: 'Entrez le prénom',
    enter_last_name: 'Entrez le nom de famille',
    enter_email: 'Entrez l\'e-mail',
    change_password_confirmation: 'Êtes-vous sûr de vouloir changer votre mot de passe ?',
    profile_update_failed: 'La mise à jour du profil'
  },
  currency: {
    select_account_currency: 'Sélectionner la devise du compte',
    cad: 'Dollar canadien (CAD)',
    usd: 'Dollar américain (USD)',
    aud: 'Dollar australien (AUD)',
    nzd: 'Dollar néo-zélandais (NZD)',
    eur: 'Euro (EUR)',
    gbp: 'Livre sterling (GBP)',
    jpy: 'Yen japonais (JPY)',
    chf: 'Franc suisse (CHF)',
    cny: 'Yuan chinois (CNY)',
  },
  short_currency: {
    cad: 'CAD',
    usd: 'USD',
    aud: 'AUD',
    nzd: 'NZD',
    eur: 'EUR',
    gbp: 'GBP',
    jpy: 'JPY',
    chf: 'CHF',
    cny: 'CNY',
  },

  type: 'Type d’exécution',
  rate: 'Taux de change',
  account_currency: 'Devise du compte',
  password: 'Mot de passe',
  confirm_password: 'Confirmer le mot de passe',
  email: 'E-mail',
  logout: 'Se déconnecter',
  login: 'Connexion',
  signup: 'Inscription',
  signin: 'Se connecter',
  signin_with: 'ou connectez-vous avec',
  login_invalid: 'E-mail ou mot de passe invalide',
  password_invalid: 'Le mot de passe ne correspond pas',
  password_rule: 'Le mot de passe doit comporter au moins 8 caractères, une lettre et un chiffre',
  reset_password: 'Réinitialiser le mot de passe',
  form_incomplete: 'Complétez le formulaire avant de vous inscrire',
  no_account: 'Pas de compte ?',
  hide_password: 'Masquer le mot de passe',
  show_password: 'Afficher le mot de passe',
  invalid_email: 'L’e-mail est invalide',
  fname: 'Prénom',
  lname: 'Nom',
  zenlot_logo: 'Icône Zenlot',
  trading_overview: 'Aperçu du trading',
  weekly_analysis: 'Analyse hebdomadaire',
  monthly_analysis: 'Analyse mensuelle',
  weekly_pips: 'Pips hebdomadaires',
  monthly_pips: 'Pips mensuels',
  active_trades: 'Transactions actives',
  trades: 'Transactions',
  net: 'Net',
  no_trade_entered: 'Aucune transaction saisie',
  available_analyses: 'Analyses disponibles',
  no_available_analyses: 'Aucune analyse disponible',
  selected_analyses: 'Analyses sélectionnées',
  no_selected_analyses: 'Aucune analyse sélectionnée',
  symbol: 'Symbole',
  tap_to_enter_trade: 'Appuyez pour saisir une transaction',
  no_internet_connection: 'Pas de connexion internet',
  duplicate_trade: 'Dupliquer la transaction',
  edit_trade: 'Modifier la transaction',
  delete_trade: 'Supprimer la transaction',
  pull_to_refresh: 'Tirer pour actualiser',
  hide_note: 'Masquer la note',
  show_note: 'Afficher la note',
  logout_confirmation: 'Êtes-vous sûr de vouloir vous déconnecter ?',
  profile: 'Profil',
  settings: 'Paramètres',
  preferences: 'Préférences',
  base_currency: 'Devise de base',
  rules: 'Règles',
  trading_rules: 'Règles de trading',
  current_password: 'Mot de passe actuel',
  new_password: 'Nouveau mot de passe',
  confirm_new_password: 'Confirmer le nouveau mot de passe',
  change_password: 'Changer le mot de passe',
  change_password_confirmation: 'Êtes-vous sûr de vouloir changer votre mot de passe ?',
  change_password_error: 'Échec du changement de mot de passe',
  history: 'Historique',
  journals: 'Journaux',
  home: 'Accueil',
  update_error: 'Erreur de mise à jour',
  password_update_failed: "Échec de la mise à jour du mot de passe",
  password_too_short: 'Le mot de passe est trop court',
  passwords_dont_match: 'Les mots de passe ne correspondent pas',
  password_updated: 'Mot de passe mis à jour avec succès',
  wrong_exisiting_password: 'Current password is wrong'
}

export default french;