const french = {
  welcome: 'Bienvenue',
  slogan: 'Maîtrisez la gestion des risques en toute simplicité',
  forex: {
    title: 'Entrer les détails de la transaction',
    edit_title: 'Modifier les détails de la transaction',
    entry_price: 'Prix d`entrée',
    entry: 'Entrée',
    ratio: 'Rapport',
    risk: 'Risque',
    reward: 'Récompense',
    pips: 'Pips',
    take_profit: 'Prendre profit',
    stop_loss: 'Arrêter la perte',
    gain: 'Gain',
    loss: 'Perte',
    lot: 'Taille du lot',
    pip_value: 'Valeur du pip',
    buy: 'Acheter',
    sell: 'Vendre',
    weekly_pips: 'Pips hebdomadaires',
    monthly_pips: 'Pips mensuels',
    sl: 'S/L',
    tp: 'T/P',
    rules: 'Entrez 3 valeurs standard de pips S/L et T/P (elles seront suggérées pour chaque transaction avec calcul automatique de S/L et T/P)',
    add_take_profit: 'Ajouter un take profit',
    add_stop_loss: 'Ajouter un stop loss',
    enter_pips: 'Entrez les pips',
    profit: 'Profit',
    take_profit_rules: 'Règles de take profit',
    stop_loss_rules: 'Règles de stop loss',
    entry_date: 'Date d’entrée',
    exit_date: 'Date de sortie',
    exit: 'Sortie',
  },
  common: {
    confirm: 'Confirmer',
    cancel: 'Annuler',
    remove: 'Supprimer',
    edit: 'Modifier',
    delete: 'Supprimer',
    duplicate: 'Dupliquer',
    save: 'Enregistrer',
    update: 'Mettre à jour',
    pending: 'En attente',
    add: 'Ajouter',
    close: 'Fermer',
    open: 'Ouvrir',
    opened: 'Ouvert',
    closed: 'Fermé',
    closed_in_profit: 'Fermé en profit',
    closed_in_loss: 'Fermé en perte',
    reached_tp: 'T/P atteint',
    reached_sl: 'S/L atteint'
  },
  placeholder: {
    entry: 'Entrez le prix d’entrée',
    forex: 'Rechercher une devise',
    profit: 'Entrez le take profit',
    loss: 'Entrez le stop loss',
    lot: 'Entrez la taille du lot',
    pips: 'Entrez la valeur du pip',
    journal: 'Commencez à écrire dans le journal...'
  },
  language: {
    language: 'Langue',
    select_language: 'Sélectionner la langue',
    en: 'Anglais',
    fr: 'Français',
    es: 'Espagnol',
  },
  user: {
    name: 'Nom',
    personal_information: 'Informations personnelles',
    last_name: 'Nom',
    first_name: 'Prénom',
    email: 'E-mail',
    enter_first_name: 'Entrez le prénom',
    enter_last_name: 'Entrez le nom de famille',
    enter_email: 'Entrez l\'e-mail',
    profile_update_failed: 'La mise à jour du profil',
    member_since: 'Date de création',
    appearance_language: 'Apparence et Langage',
    appearance: 'Apparence',
    appearance_language_desc: 'Choisissez votre langue et l\'apparence de l\'application.',
    select_theme: 'Sélectionnez le thème',
    preview_title: 'Aperçu',
    preview_desc: 'Voici à quoi ressemblent le texte et les surfaces avec le thème sélectionné.',
    security: 'Sécurité',
    authentication_method: 'Méthode d\'authentification',
    timezone: 'Fuseau horaire',
    edit_profile: 'Modifier le profil'
  },
  appearance: {
    light: 'Lumière',
    dark: 'Sombre',
    system: 'Système'
  },
  currency: {
    select_account_currency: 'Sélectionner la devise du compte',
    cad: 'Dollar canadien (CAD)',
    usd: 'Dollar américain (USD)',
    aud: 'Dollar australien (AUD)',
    nzd: 'Dollar néo-zélandais (NZD)',
    eur: 'Euro (EUR)',
    gbp: 'Livre sterling (GBP)',
    jpy: 'Yen japonais (JPY)',
    chf: 'Franc suisse (CHF)',
    cny: 'Yuan chinois (CNY)',
  },
  short_currency: {
    cad: 'CAD',
    usd: 'USD',
    aud: 'AUD',
    nzd: 'NZD',
    eur: 'EUR',
    gbp: 'GBP',
    jpy: 'JPY',
    chf: 'CHF',
    cny: 'CNY',
  },
  password: {
    password: 'Mot de passe',
    confirm: 'Confirmer le mot de passe',
    change: 'Changer le mot de passe',
    change_desc: 'Mettez à jour votre mot de passe pour sécuriser votre compte.',
    change_confirmation: 'Êtes-vous sûr de vouloir changer votre mot de passe ?',
    mismatch: 'Le mot de passe ne correspond pas',
    rule: 'Le mot de passe doit comporter au moins 8 caractères, une lettre et un chiffre',
    reset: 'Réinitialiser le mot de passe',
    hide: 'Masquer le mot de passe',
    show: 'Afficher le mot de passe',
    current: 'Mot de passe actuel',
    current_required: 'Le mot de passe actuel est requis',
    new: 'Nouveau mot de passe',
    confirm_required: 'Veuillez confirmer votre nouveau mot de passe',
    confirm_new: 'Confirmer le nouveau mot de passe',
    new_required: 'Le nouveau mot de passe est requis',
    change_password: 'Changer le mot de passe',
    change_error: 'Échec du changement de mot de passe',
    update_failed: "Échec de la mise à jour du mot de passe",
    too_short: 'Le mot de passe doit comporter au moins 8 caractères.',
    updated: 'Mot de passe mis à jour avec succès',
    current_error: 'Le mot de passe actuel est incorrect',
    strength: 'Force du mot de passe',
    strong: 'Fort',
    moderate: 'Modéré',
    weak: 'Faible',
    very_weak: 'Très faible',
    same_as_current: 'Le nouveau mot de passe doit être différent du mot de passe actuel.',
  
  },
  default: {
    tp: 'T/P par défaut',
    sl: 'S/L par défaut',
    lot: 'Taille de lot par défaut',
  
  },
  type: 'Type d’exécution',
  rate: 'Taux de change',
  account_currency: 'Devise du compte',
  confirm_password: 'Confirmer le mot de passe',
  email: 'E-mail',
  logout: 'Se déconnecter',
  login: 'Connexion',
  signup: 'Inscription',
  signin: 'Se connecter',
  signin_with: 'ou connectez-vous avec',
  login_invalid: 'E-mail ou mot de passe invalide',
  form_incomplete: 'Complétez le formulaire avant de vous inscrire',
  no_account: 'Pas de compte ?',
  invalid_email: 'L’e-mail est invalide',
  fname: 'Prénom',
  lname: 'Nom',
  zenlot_logo: 'Icône Zenlot',
  trading_overview: 'Aperçu du trading',
  weekly_analysis: 'Analyse hebdomadaire',
  monthly_analysis: 'Analyse mensuelle',
  weekly_pips: 'Pips hebdomadaires',
  monthly_pips: 'Pips mensuels',
  active_trades: 'Transactions actives',
  trades: 'Transactions',
  net: 'Net',
  no_trade_entered: 'Aucune transaction saisie',
  available_analyses: 'Analyses disponibles',
  no_available_analyses: 'Aucune analyse disponible',
  selected_analyses: 'Analyses sélectionnées',
  no_selected_analyses: 'Aucune analyse sélectionnée',
  symbol: 'Symbole',
  tap_to_enter_trade: 'Appuyez pour saisir une transaction',
  no_internet_connection: 'Pas de connexion internet',
  duplicate_trade: 'Dupliquer la transaction',
  edit_trade: 'Modifier la transaction',
  delete_trade: 'Supprimer la transaction',
  pull_to_refresh: 'Tirer pour actualiser',
  hide_note: 'Masquer la note',
  show_note: 'Afficher la note',
  logout_confirmation: 'Êtes-vous sûr de vouloir vous déconnecter ?',
  profile: 'Profil',
  settings: 'Paramètres',
  preferences: 'Préférences',
  base_currency: 'Devise de base',
  rules: 'Règles',
  trading_rules: 'Règles de trading',
  history: 'Historique',
  journals: 'Journaux',
  home: 'Accueil',
  update_error: 'Erreur de mise à jour',
  no_active_trades: 'Aucune transaction active',
  add_analytic_overview: "Appuyez pour ajouter un aperçu analytique",
  success: 'Succès',
  show_gain_in_loss: 'Afficher le gain/perte dans ',
  show_gain_in_loss_desc: 'Basculez entre l\'affichage du gain/perte en pips ou en devise de compte.',
  modify_trading_rules: 'Modifier vos règles de trading',
  app_information: 'Informations sur l\'application',
  app_version: 'Version de l\'application',
  last_update: 'Dernière mise à jour',
  account_actions: 'Actions du compte',
  wins: 'Gains',
  losses: 'Pertes',
  this_week: 'Cette semaine',
  recent: 'Récent',
  this_month: 'Ce mois-ci',
  quick_search: 'Recherche rapide',
  trade_history: 'Historique des transactions',
  search_trades: 'Rechercher des transactions',
  search_trades_helper_text: 'Recherchez par symbole, type d\'exécution, statut ou contenu du journal.',
  no_trade_history: 'Aucun historique de transactions trouvé',
  start_trading_message: 'Commencez à trader pour voir votre historique de transactions ici.',
  view_details: 'Voir les détails',
  all_trades: "Tous",
  load_more: 'Charger plus',
  journal: 'Journal',
}

export default french;